
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jun 29 22:43:56 CEST 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PP = 14;
  public static final int MM = 15;
  public static final int CONST = 5;
  public static final int NUMCONST = 52;
  public static final int QUESTIONMARK = 17;
  public static final int CASE = 36;
  public static final int CONTINUE = 49;
  public static final int LPAREN = 10;
  public static final int SEMI = 13;
  public static final int L = 41;
  public static final int G = 39;
  public static final int MINUS = 18;
  public static final int E = 45;
  public static final int RPAREN = 11;
  public static final int AND = 43;
  public static final int OR = 44;
  public static final int COMMA = 6;
  public static final int CLASS = 28;
  public static final int DIV = 22;
  public static final int GEQ = 40;
  public static final int PLUS = 20;
  public static final int IF = 30;
  public static final int DOT = 46;
  public static final int EOF = 0;
  public static final int RETURN = 26;
  public static final int EQUAL = 7;
  public static final int NEW = 19;
  public static final int error = 1;
  public static final int MUL = 21;
  public static final int MOD = 23;
  public static final int IDENT = 51;
  public static final int BREAK = 27;
  public static final int VOID = 12;
  public static final int EQ = 48;
  public static final int SWITCH = 32;
  public static final int NOTSAME = 38;
  public static final int SAME = 37;
  public static final int COLON = 16;
  public static final int LBRACE = 3;
  public static final int ELSE = 31;
  public static final int LSQUARE = 8;
  public static final int ENUM = 29;
  public static final int READ = 24;
  public static final int CHARCONST = 53;
  public static final int RSQUARE = 9;
  public static final int WHILE = 34;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 54;
  public static final int EXTENDS = 35;
  public static final int PROG = 2;
  public static final int LEQ = 42;
  public static final int AT = 50;
  public static final int PRINT = 25;
  public static final int DO = 33;
  public static final int NOTEQ = 47;
}

